name: Run python API tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build image
      run: docker build -t python-api-tests:latest .

    - name: Run api tests container
      run: docker run python-api-tests:latest
    
    # # store html test report
    # - name: Upload HTML Report
    #   uses: actions/upload-artifact@v4
    #   if: ${{ !cancelled() }}
    #   with:
    #     name: html-report
    #     path: ./report.html  