name: Run python API tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
        BASE_URL: ${{ secrets.BASE_URL }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Build image
      run: docker build -t python-api-tests:latest .

    - name: Run api tests container
      run: docker run -e BASE_URL="$BASE_URL" python-api-tests:latest
